### ISSUE TITLE
Groups not saving when group name has a capital letter

### ISSUE THREAD

**Issue by xXBuilderBXx** [KaiKikuchi/SimplePermissions#1]
Hey there Kai this plugin for sponge and many other permission plugins are not working for my version of sponge or forge.
Minecraft: 1.8.9
SpongeApi 4.2
SpongeForge: 4.2 beta 1653
Forge: 11.15.1.1890

The plugin is working very well for the default group but when i try to create a group using pgroup or add a permission it does not get saved to the groups.conf and the permissions i add do not work at all

**Comment by KaiKikuchi** [comment]
Try adding a player to the group too.

**Comment by xXBuilderBXx** [comment]
Thanks for the fast reply when i try to add myself to the group it seems to remove the group from group.conf when i run /sponge plugins reload

**Comment by xXBuilderBXx** [comment]
Yup i just tested it when i add myself to a diffrent group than default it resets the group.conf file

**Comment by KaiKikuchi** [comment]
Okay, thanks for your report.

The plugin is being reported to work properly with Sponge API 4.1, 4.2 and 5.0 (I'm using this last version). I will make a 4.2 test server tomorrow.

If possible, please try these steps:
- Stop your server
- Delete all your simplepermissions config files
- Start your server
- Make a new group
- Add yourself to that group
- Reload the server

**Comment by xXBuilderBXx** [comment]
Ok i just tested it with 2 groups Test1 and Test2
Whenever i add myself to the group Test1 it gets wiped from group.conf but Test2 and default stays
Then i try to add myself to group Test2 and it gets wiped from group.conf  leaving the default group

It appears to be wiping the groups whenver someone gets put in that group

**Comment by KaiKikuchi** [comment]
Okay. I will make a SpongeAPI 4.2 test server and fix the issue tomorrow. Thank you very much for your report.

**Comment by xXBuilderBXx** [comment]
Ok thanks for now i can just add permissions for the default group that everyone can use

**Comment by KaiKikuchi** [comment]
I have tested SimplePermissions v.0.9.9 with spongeforge-1.8.9-1890-4.2.0-BETA-1666 and it works fine on a clean install (no other plugins/mods other than SimplePermissions/SpongeForge).

You may want to add more info about your server, like plugins and mods you're using, and the fml server log.

**Comment by xXBuilderBXx** [comment]
Sorry to bring this back up but the issue i was facing is because i was using a capital in the group name lol

**Comment by KaiKikuchi** [comment]
Oh okay, thank you for your report!
