### ISSUE TITLE
Question: about parent group

### ISSUE THREAD

**Issue by 5igm** [KaiKikuchi/SimplePermissions#3]
How can I make a group and put all of its permissions to built-in group?
If I use
/pgroup GroupA parent GroupB
will GroupB own all of the permissions of GroupA?

**Comment by KaiKikuchi** [comment]
if you do `/pgroup GroupA parent GroupB`, it means that GroupA's parent will be GroupB. GroupA will inherit all permissions from GroupB. e.g. GroupB has the permission "minecraft.command.tell", and you do `/group GroupA parent GroupB`. Now players on GroupA will have GroupB's permissions too.
