### ISSUE TITLE
How can I make people join a group when they join the server at first time?

### ISSUE THREAD

**Issue by 5igm** [KaiKikuchi/SimplePermissions#4]
As you said, there is actually no default group in SimplePermission. But, how can I make people join a  group when they join the server at first time? They don't have any permissions to use anything.

**Comment by KaiKikuchi** [comment]
I've never said there isn't a default group. I said there is a group named "default", and that is the default group. You add permissions to group "default", and everyone will have that permissions.

[Just read.](https://github.com/KaiKikuchi/SimplePermissions/issues/2#issuecomment-240388566)

**Comment by KaiKikuchi** [comment]
Also please use the Sponge thread if you have questions. The Issues tracker is mostly for issues.

**Comment by 5igm** [comment]
Thank you very much!
